// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwng3Jj8Dg_0Fi7yPrGmvJxebtI8gPS54',
    appId: '1:729517614264:web:760085377c5778c333004d',
    messagingSenderId: '729517614264',
    projectId: 'jonihoney-app',
    authDomain: 'jonihoney-app.firebaseapp.com',
    storageBucket: 'jonihoney-app.firebasestorage.app',
    measurementId: 'G-B0GTLWM08M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgiT-pCC2gTrv-zoCiuRSB7ru1wSZuyc',
    appId: '1:729517614264:android:2a05717405d39c5a33004d',
    messagingSenderId: '729517614264',
    projectId: 'jonihoney-app',
    storageBucket: 'jonihoney-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGoAjcXt-JFmjPhJ4xfXbjqnTPVNtofU',
    appId: '1:729517614264:ios:b5ce7c6874e9736633004d',
    messagingSenderId: '729517614264',
    projectId: 'jonihoney-app',
    storageBucket: 'jonihoney-app.firebasestorage.app',
    iosBundleId: 'com.example.jonihoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdGoAjcXt-JFmjPhJ4xfXbjqnTPVNtofU',
    appId: '1:729517614264:ios:b5ce7c6874e9736633004d',
    messagingSenderId: '729517614264',
    projectId: 'jonihoney-app',
    storageBucket: 'jonihoney-app.firebasestorage.app',
    iosBundleId: 'com.example.jonihoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwng3Jj8Dg_0Fi7yPrGmvJxebtI8gPS54',
    appId: '1:729517614264:web:2a0eac8432710d8d33004d',
    messagingSenderId: '729517614264',
    projectId: 'jonihoney-app',
    authDomain: 'jonihoney-app.firebaseapp.com',
    storageBucket: 'jonihoney-app.firebasestorage.app',
    measurementId: 'G-SCF7K69DLC',
  );
}
